'use client'

import { create } from 'zustand'
import type { CompetitorStyleArtifact } from '@/lib/artifacts/competitor-style-artifact'
import type { DesignReviewResult } from '@/lib/artifacts/design-review-artifact'
import type { DesignReinforcementArtifact } from '@/lib/artifacts/design-reinforcement-artifact'
import type { BriefData } from '@/lib/artifacts/product-brief-artifact'
import { confirmProductBrief, reviseProductBrief } from '@/lib/product/brief-lifecycle'

export type { BriefData } from '@/lib/artifacts/product-brief-artifact'

export const CANVAS_ITEM_TYPES=['image','video','text','frame','generator','rectangle','ellipse','line','arrow','star','polygon','drawing','brief','research','competitor-style','design-reinforcement'] as const
export type CanvasItemType=typeof CANVAS_ITEM_TYPES[number]
export type CanvasTool='select'|'hand'|'text'|'frame'|'rectangle'|'ellipse'|'line'|'arrow'|'star'|'polygon'|'pencil'|'generator'
export type ResearchData={topic:string;summary:string;marketSize:string;competitors:{name:string;price:string;note:string}[];trends:string[];sources:{title:string;url:string}[]}
export type CanvasItem={id:string;type:CanvasItemType;title:string;src?:string;text?:string;prompt?:string;status?:'idle'|'generating'|'done'|'error';x:number;y:number;width:number;height:number;zIndex:number;hidden?:boolean;locked?:boolean;groupId?:string;fill?:string;stroke?:string;strokeWidth?:number;path?:string;layout?:'auto'|'manual';aspectLocked?:boolean;quality?:'1K'|'2K'|'4K'|'auto'|'high'|'medium'|'low';count?:number;ratio?:string;model?:string;error?:string;fontSize?:number;fontWeight?:number;lineHeight?:number;align?:'left'|'center'|'right';stylePreset?:string;brief?:BriefData;research?:ResearchData;competitorStyle?:CompetitorStyleArtifact;designReinforcement?:DesignReinforcementArtifact;sourceStyleBoardId?:string;sourceDirectionId?:string;sourceProductId?:string;sourceProductVersion?:number;stale?:boolean;staleReason?:string;designIteration?:number;designReview?:DesignReviewResult}
export type AlignMode='left'|'centerX'|'right'|'top'|'centerY'|'bottom'|'distributeX'|'distributeY'
type Snapshot={items:CanvasItem[];selectedIds:string[]};export type CanvasLog={id:string;label:string;at:number}
type BriefLifecycleState={addBrief:(id:string,title:string,brief:BriefData)=>void;reviseBrief:(id:string,brief:BriefData)=>void;confirmBrief:(id:string)=>void;addResearch:(id:string,title:string,research:ResearchData)=>void;addCompetitorStyle:(id:string,title:string,artifact:CompetitorStyleArtifact)=>void;addDesignReinforcement:(id:string,title:string,artifact:DesignReinforcementArtifact)=>void}
type State=BriefLifecycleState & {projectId:string|null;items:CanvasItem[];selectedIds:string[];tool:CanvasTool;clipboard:CanvasItem[];past:Snapshot[];future:Snapshot[];logs:CanvasLog[];setProjectId:(projectId:string)=>void;hydrateDocument:(document:{items:unknown[];logs:CanvasLog[]})=>void;setTool:(t:CanvasTool)=>void;selectItems:(ids:string[])=>void;checkpoint:(label:string)=>void;addItem:(item:Omit<CanvasItem,'zIndex'>,label?:string)=>void;updateItem:(id:string,patch:Partial<CanvasItem>,historyOrLabel?:boolean|string,label?:string)=>void;moveItems:(moves:{id:string;x:number;y:number}[])=>void;moveItem:(id:string,x:number,y:number)=>void;commitMove:(label?:string)=>void;addImage:(id:string,src:string,title:string,prompt?:string)=>void;addText:(id:string,text:string,title:string)=>void;removeSelected:()=>void;duplicateSelected:()=>void;copy:()=>void;cut:()=>void;paste:()=>void;moveLayer:(d:'front'|'back'|'up'|'down')=>void;toggleLocked:()=>void;toggleHidden:()=>void;group:()=>void;ungroup:()=>void;alignSelected:(mode:AlignMode)=>void;undo:()=>void;redo:()=>void}
const allowed=new Set<string>(CANVAS_ITEM_TYPES)
const clone=(items:CanvasItem[])=>items.map(item=>({...item}));const snap=(s:State):Snapshot=>({items:clone(s.items),selectedIds:[...s.selectedIds]});const id=()=>crypto.randomUUID()
export const useCanvasStore=create<State>((set,get)=>({
 projectId:null,items:[],selectedIds:[],tool:'select',clipboard:[],past:[],future:[],logs:[],
 setProjectId:projectId=>set({projectId}),
 hydrateDocument:document=>set({items:clone(document.items.filter((item):item is CanvasItem=>Boolean(item&&typeof item==='object'&&allowed.has((item as {type?:string}).type??'')))),logs:[...(document.logs??[])],selectedIds:[],past:[],future:[]}),
 setTool:tool=>set({tool}),
 selectItems:ids=>{const old=get().selectedIds;if(old.length===ids.length&&old.every((value,index)=>value===ids[index]))return;set({selectedIds:ids})},
 checkpoint:label=>set(s=>({past:[...s.past.slice(-79),snap(s)],future:[],logs:[...s.logs,{id:id(),label,at:Date.now()}]})),
 addItem:(item,label)=>{get().checkpoint(label||`创建${item.title}`);set(s=>({items:[...s.items,{...item,zIndex:Math.max(0,...s.items.map(i=>i.zIndex))+1}],selectedIds:[item.id]}))},
 updateItem:(itemId,patch,historyOrLabel=false,label='修改对象')=>{const history=typeof historyOrLabel==='string'||historyOrLabel;const resolved=typeof historyOrLabel==='string'?historyOrLabel:label;if(history)get().checkpoint(resolved);set(s=>({items:s.items.map(i=>i.id===itemId?{...i,...patch}:i)}))},
 moveItems:moves=>set(s=>({items:s.items.map(i=>{const move=moves.find(entry=>entry.id===i.id);return move?{...i,x:move.x,y:move.y}:i})})),
 moveItem:(itemId,x,y)=>set(s=>({items:s.items.map(i=>i.id===itemId?{...i,x,y}:i)})),
 commitMove:(label='移动对象')=>set(s=>({logs:[...s.logs,{id:id(),label,at:Date.now()}]})),
addImage:(itemId,src,title,prompt)=>{if(get().items.some(item=>item.id===itemId)){set({selectedIds:[itemId]});return}const right=get().items.length?Math.max(...get().items.map(item=>item.x+item.width))+64:120;get().addItem({id:itemId,type:'image',title,src,prompt,x:right,y:80,width:460,height:460},'Agent 添加图像')},
 addBrief:(itemId,title,brief)=>{if(get().items.some(item=>item.id===itemId)){set({selectedIds:[itemId]});return}const right=get().items.length?Math.max(...get().items.map(item=>item.x+item.width))+64:80;get().addItem({id:itemId,type:'brief',title,brief,x:right,y:80,width:460,height:840},'Agent 创建 Product Brief')},
 reviseBrief:(itemId,nextBrief)=>{const currentItem=get().items.find(item=>item.id===itemId);if(!currentItem?.brief)return;const revised=reviseProductBrief(currentItem.brief,nextBrief,new Date().toISOString());if(revised===currentItem.brief)return;const invalidatesDownstream=currentItem.brief.status==='confirmed';get().checkpoint(invalidatesDownstream?'修改已确认 Product Brief':'编辑 Product Brief');set(s=>({items:s.items.map(item=>{if(item.id===itemId)return{...item,title:`${revised.productName} · Brief`,brief:revised};if(!invalidatesDownstream)return item;const matches=item.sourceProductId===revised.productId||item.designReinforcement?.product_id===revised.productId;return matches?{...item,stale:true,staleReason:`Product Brief 已更新为 v${revised.version}，请重新运行下游流程`}:item})}))},
 confirmBrief:itemId=>{const currentItem=get().items.find(item=>item.id===itemId);if(!currentItem?.brief||currentItem.brief.status==='confirmed')return;get().checkpoint('确认 Product Brief');const confirmed=confirmProductBrief(currentItem.brief,new Date().toISOString());set(s=>({items:s.items.map(item=>item.id===itemId?{...item,brief:confirmed}:item)}))},
 addResearch:(itemId,title,research)=>{if(get().items.some(item=>item.id===itemId)){set({selectedIds:[itemId]});return}const right=get().items.length?Math.max(...get().items.map(item=>item.x+item.width))+64:80;get().addItem({id:itemId,type:'research',title,research,x:right,y:80,width:460,height:780},'Agent 创建市场调研')},
 addCompetitorStyle:(itemId,title,competitorStyle)=>{if(get().items.some(item=>item.id===itemId)){set({selectedIds:[itemId]});return}const right=get().items.length?Math.max(...get().items.map(item=>item.x+item.width))+64:80;get().addItem({id:itemId,type:'competitor-style',title,competitorStyle,x:right,y:80,width:620,height:780},'Agent 创建竞品视觉板')},
 addDesignReinforcement:(itemId,title,designReinforcement)=>{if(get().items.some(item=>item.id===itemId)){set({selectedIds:[itemId]});return}const right=get().items.length?Math.max(...get().items.map(item=>item.x+item.width))+64:80;get().addItem({id:itemId,type:'design-reinforcement',title,designReinforcement,sourceProductId:designReinforcement.product_id,sourceProductVersion:designReinforcement.product_brief.version,stale:false,x:right,y:80,width:720,height:920},'Agent 创建设计强化 Artifact')},
 addText:(itemId,text,title)=>{if(get().items.some(item=>item.id===itemId)){set({selectedIds:[itemId]});return}get().addItem({id:itemId,type:'text',title,text,x:120,y:120,width:300,height:120},'Agent 添加文字')},
 removeSelected:()=>{const s=get();if(!s.selectedIds.length)return;s.checkpoint('删除对象');set({items:s.items.filter(i=>!s.selectedIds.includes(i.id)),selectedIds:[]})},
 copy:()=>set(s=>({clipboard:clone(s.items.filter(i=>s.selectedIds.includes(i.id)))})),cut:()=>{get().copy();get().removeSelected()},
 paste:()=>{const s=get();if(!s.clipboard.length)return;s.checkpoint('粘贴对象');const groups=new Map<string,string>();const copies=s.clipboard.map((item,index)=>{if(item.groupId&&!groups.has(item.groupId))groups.set(item.groupId,id());return{...item,id:id(),x:item.x+32,y:item.y+32,zIndex:Math.max(0,...s.items.map(entry=>entry.zIndex))+index+1,groupId:item.groupId?groups.get(item.groupId):undefined}});set({items:[...s.items,...copies],selectedIds:copies.map(item=>item.id)})},duplicateSelected:()=>{get().copy();get().paste()},
 moveLayer:direction=>{const s=get();if(!s.selectedIds.length)return;s.checkpoint('调整图层');const levels=s.items.map(i=>i.zIndex);set({items:s.items.map(i=>!s.selectedIds.includes(i.id)?i:{...i,zIndex:direction==='front'?Math.max(...levels)+1:direction==='back'?Math.min(...levels)-1:direction==='up'?i.zIndex+1:i.zIndex-1})})},
 toggleLocked:()=>{const s=get();const value=s.items.find(i=>s.selectedIds.includes(i.id));if(!value)return;s.checkpoint('锁定/解锁');set({items:s.items.map(i=>s.selectedIds.includes(i.id)?{...i,locked:!value.locked}:i)})},
 toggleHidden:()=>{const s=get();const value=s.items.find(i=>s.selectedIds.includes(i.id));if(!value)return;s.checkpoint('显示/隐藏');set({items:s.items.map(i=>s.selectedIds.includes(i.id)?{...i,hidden:!value.hidden}:i)})},
 group:()=>{const s=get();if(s.selectedIds.length<2)return;s.checkpoint('创建编组');const groupId=id();set({items:s.items.map(i=>s.selectedIds.includes(i.id)?{...i,groupId}:i)})},
 ungroup:()=>{const s=get();s.checkpoint('解除编组');set({items:s.items.map(i=>s.selectedIds.includes(i.id)?{...i,groupId:undefined}:i)})},
 alignSelected:mode=>{const s=get();const picked=s.items.filter(i=>s.selectedIds.includes(i.id)&&!i.locked);if(picked.length<2)return;s.checkpoint('对齐对象');const minX=Math.min(...picked.map(i=>i.x)),maxR=Math.max(...picked.map(i=>i.x+i.width)),minY=Math.min(...picked.map(i=>i.y)),maxB=Math.max(...picked.map(i=>i.y+i.height));let patch:(i:CanvasItem)=>Partial<CanvasItem>;if(mode==='left')patch=()=>({x:minX});else if(mode==='right')patch=i=>({x:maxR-i.width});else if(mode==='centerX')patch=i=>({x:(minX+maxR)/2-i.width/2});else if(mode==='top')patch=()=>({y:minY});else if(mode==='bottom')patch=i=>({y:maxB-i.height});else if(mode==='centerY')patch=i=>({y:(minY+maxB)/2-i.height/2});else if(mode==='distributeX'){const sorted=[...picked].sort((a,b)=>a.x-b.x),gap=(maxR-minX-sorted.reduce((n,i)=>n+i.width,0))/(sorted.length-1);let cursor=minX;const positions=new Map<string,number>();for(const item of sorted){positions.set(item.id,cursor);cursor+=item.width+gap}patch=i=>({x:positions.get(i.id)})}else{const sorted=[...picked].sort((a,b)=>a.y-b.y),gap=(maxB-minY-sorted.reduce((n,i)=>n+i.height,0))/(sorted.length-1);let cursor=minY;const positions=new Map<string,number>();for(const item of sorted){positions.set(item.id,cursor);cursor+=item.height+gap}patch=i=>({y:positions.get(i.id)})}set({items:s.items.map(i=>s.selectedIds.includes(i.id)&&!i.locked?{...i,...patch(i)}:i)})},
 undo:()=>set(s=>{const previous=s.past.at(-1);return previous?{...previous,past:s.past.slice(0,-1),future:[snap(s),...s.future],logs:[...s.logs,{id:id(),label:'撤销',at:Date.now()}]}:s}),
 redo:()=>set(s=>{const next=s.future[0];return next?{...next,past:[...s.past,snap(s)],future:s.future.slice(1),logs:[...s.logs,{id:id(),label:'重做',at:Date.now()}]}:s}),
}))
